### ISSUE TITLE
EUDATSearchPID() seems to return too much info in some case(s)

### ISSUE THREAD

**Issue by samuell** [EUDAT-B2SAFE/B2SAFE-core#17]
We try to get the iRODS 4 compatible version of B2SAFE to create PID handles through the rule system.

Manually creating PIDs via epicclient.py works fine (we have logged in on https://epic4.storage.surfsara.nl/v2_B/handles/*****/ to check!)

We get problems when using the EUDATCreatePID() rule though.

We get a "PID already exists" message in rodsLog when we try to manually create a PID with the following rule file (run with irule -F <filename>):

```cpp
testRule {
        msiWriteRodsLog("TEST EUDATCreatePID: src *src", *status);
        EUDATCreatePID("None", *src, "None", bool("false"), *newPID);
}
INPUT *src="/tempZone/home/rods/test.txt"
OUTPUT ruleExecOut
```

The log line that we see is:

```
Jan 28 16:56:59 pid:17046 NOTICE: writeLine: inString = INFO: PID already exists (credentials from os:https://epic4.storage.surfsara.nl/v2_B/handles ***** ***** application/json
[ searchHandle ] URI https://epic4.storage.surfsara.nl/v2_B/handles/*****/?URL=irods://localhost:1247/tempZone/home/rods/test.txt
[ checkresponsecode ] .....
[ searchHandle ] Request completed. No error,                     operation successful 200
empty)
```

Looking at where the "PID already exists" string is generated, led me to line 74 in pid-service.re, where I see that th `EUDATCreatePID()` function runs `EUDATSearchPID()`, and checks whether the output of that is "empty" or "None".

So, I added one line in pid-service.re to see the output of `EUDATSearchPID()`:

```cpp
EUDATCreatePID(*parent_pid, *path, *ror, *iCATCache, *newPID) {
    logInfo("create pid for *path and save *ror as ror");
    getEpicApiParameters(*credStoreType, *credStorePath, *epicApi, *serverID, *epicDebug);

    #check if PID already exists

    EUDATSearchPID(*path, *existing_pid);
    logInfo("EXISTING_PID: *existing_pid END_EXISTING_PID"); # <-- I added this line!

    if((*existing_pid == "empty") || (*existing_pid == "None")) {
        # create PID
        EUDATePIDcreate(*path, *newPID);

        if (*iCATCache == bool("true")) {
            # Add PID into iCAT
            logInfo("Saving PID into field AVU -PID- of iCAT *path with PID = *newPID");
            EUDATiPIDcreate(*path, *newPID);
        }

    }
    else {
        *newPID = *existing_pid;
        logInfo("PID already exists (*newPID)");
    }
```

Then, in rodsLog, I see the following output, from my extra log line:

```log
Jan 28 16:53:57 pid:16873 NOTICE: writeLine: inString = INFO: EXISTING_PID: credentials from os:https://epic4.storage.surfsara.nl/v2_B/handles ***** ***** application/json
[ searchHandle ] URI https://epic4.storage.surfsara.nl/v2_B/handles/*****/?URL=irods://localhost:1247/tempZone/home/rods/test.txt
[ checkresponsecode ] .....
[ searchHandle ] Request completed. No error,                     operation successful 200
empty END_EXISTING_PID
```

Do you see the little string "empty" there? AFAIS, that is the only thing that should be within "EXISTING_PID" and "END_EXISTING_PID" ... but instead we see this long string of output!

Thus, the if-statement in EUDATCreatePID (around line 74 in `pid-service.re`) will not work.

Any thoughts on this?

**Comment by ccacciari** [comment]
is the debug option related to the python epic client set to true?
It should be false when the client is invoked by iRODS rules, otherwise 
the debug output "confuses" the iRODS rules.

Regards,
Claudio

**Comment by samuell** [comment]
@ccacciari Thanks! Indeed, I think it is, will try turning it off!

**Comment by samuell** [comment]
@ccacciari Sorry, could you remind me where this is set? I seem to have forgotten it , and I don't find the setting neither in epicclient.py itself nor in b2safe.config?

**Comment by samuell** [comment]
@ccacciari Found it now, in the credentials file! (Don't know how I managed to forget that ...)
