### ISSUE TITLE
Error in `irodsReServer': double free or corruption

### ISSUE THREAD

**Issue by janiheikkinen** [EUDAT-B2SAFE/B2SAFE-core#19]
In iRODSv4.0.3 when a rule is called through pending rule-execution, the rule engine crashes in  double free or corruption error. The following is the delayed rule as seen through iqstat. The rule engine crashes after the first call to logInfo and before executing the first action inside  [processPIDCommandFile(*file)](https://github.com/EUDAT-B2SAFE/B2SAFE-core/blob/release-3.0/rulebase/eudat.re) .

```
  if(errorcode(msiObjStat(*file,*out)) >= 0) {
            logInfo("*file exists");
            processPIDCommandFile(*file);
        } else {
            logInfo("*file does not exist yet");
            EUDATProcessErrorUpdatePID(*file);
        }
```

Here's  an excerpt from reLog :

NOTICE: writeLine: inString = INFO: /zone/replicate/test.dat.pid.update exists
*** glibc detected *** irodsReServer: double free or corruption (!prev): 0x0000000001c42760 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x75e66)[0x7fc3a8a70e66]
/lib64/libc.so.6(+0x789b3)[0x7fc3a8a739b3]
irodsReServer(freeDataObjInfo+0x37)[0x493787]
irodsReServer(freeAllDataObjInfo+0x1c)[0x4937bc]
irodsReServer(_Z25freeRuleExecInfoInternalsP12RuleExecInfoi+0x67)[0x71a547]
irodsReServer(_Z22freeRuleExecInfoStructP12RuleExecInfoi+0x9)[0x71a5d9]
irodsReServer(_Z8execRulePcPP4nodejiP3envP12RuleExecInfoiP8rError_tP6region+0x3d6)[0x6bfde6]
irodsReServer(_Z11execAction3PcPP4nodejiS1_P3envP12RuleExecInfoiP8rError_tP6region+0x91)[0x6bff71]
irodsReServer(_Z17evaluateFunction3P4nodeiS0_P3envP12RuleExecInfoiP8rError_tP6region+0x66b)[0x6c110b]
irodsReServer(_Z27evaluateFunctionApplicationP4nodeS0_iS0_P12RuleExecInfoiP3envP8rError_tP6region+0xe7)[0x6c14d7]
irodsReServer(_Z19evaluateExpression3P4nodeiiP12RuleExecInfoiP3envP8rError_tP6region+0x240)[0x6bec80]
irodsReServer(_Z15evaluateActionsP4nodeS0_iP12RuleExecInfoiP3envP8rError_tP6region+0xe6)[0x6bf096]
irodsReServer(_Z17evaluateFunction3P4nodeiS0_P3envP12RuleExecInfoiP8rError_tP6region+0x92e)[0x6c13ce]
irodsReServer(_Z27evaluateFunctionApplicationP4nodeS0_iS0_P12RuleExecInfoiP3envP8rError_tP6region+0xe7)[0x6c14d7]
irodsReServer(_Z19evaluateExpression3P4nodeiiP12RuleExecInfoiP3envP8rError_tP6region+0x240)[0x6bec80]
irodsReServer(_Z15evaluateActionsP4nodeS0_iP12RuleExecInfoiP3envP8rError_tP6region+0xe6)[0x6bf096]
irodsReServer(_Z19evaluateExpression3P4nodeiiP12RuleExecInfoiP3envP8rError_tP6region+0x153)[0x6beb93]
irodsReServer(_Z11computeNodeP4nodeS0_P3envP12RuleExecInfoiP8rError_tP6region+0xe1)[0x6c1901]
irodsReServer(_Z25parseAndComputeExpressionPcP3envP12RuleExecInfoiP8rError_tP6region+0x270)[0x6c1bf0]
irodsReServer(_Z32parseAndComputeExpressionAdapterPcP12MsParamArrayiP12RuleExecInfoiP6region+0xef)[0x6c297f]
irodsReServer(_Z13applyRuleBasePcP12MsParamArrayiP12RuleExecInfoi+0x176)[0x707b86]
irodsReServer(_Z11runRuleExecP12reExecProc_t+0x5a)[0x53650a]
irodsReServer(_Z18reServerSingleExecP8rsComm_tPci+0x319)[0x538e69]
irodsReServer(main+0x3ad)[0x4874bd]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x7fc3a8a19d5d]
irodsReServer[0x485759]
======= Memory map: ========
00400000-0087a000 r-xp 00000000 fd:02 148812                             /var/lib/irods/iRODS/server/bin/irodsReServer
00a79000-00a8e000 rw-p 00479000 fd:02 148812                             /var/lib/irods/iRODS/server/bin/irodsReServer

Error was detected on RHEL6.6 and Ubuntu 14.04.1 LTS.

**Comment by janiheikkinen** [comment]
Does this relate to https://github.com/irods/irods/issues/2250 ?

**Comment by janiheikkinen** [comment]
Running the following rule through irule causes rule engine to segfault. v4.1.0 built from master (cloned 150303).

```
test_delay {
    delay("<PLUSET>15s</PLUSET>") {
        writeLine("serverLog","INFO: *cmdPath");
    }  
}
INPUT *cmdPath="/zone/home/rods/test.update"
OUTPUT ruleExecOut
```

```
Core was generated by `irodsReServer'.
Program terminated with signal 11, Segmentation fault.
#0  0x000000000096e122 in touchupPackedRei (rsComm=Cannot access memory at address 0x7fffd275b858
) at /mnt/irods/iRODS/server/re/src/reStruct.cpp:435
435         rsComm->clientUser = *( myRei->uoic );
```


```
$ ienv
NOTICE: Release Version = rods4.1.0, API Version = d
NOTICE: irods_session_environment_file - /home/irods/.irods/irods_environment.json.14302
NOTICE: irods_user_name - rods
NOTICE: irods_host - f.q.d.n
NOTICE: xmsg_host is not defined
NOTICE: irods_home - /zone/home/rods
NOTICE: irods_cwd - /zone/home/rods
NOTICE: irods_authentication_scheme is not defined
NOTICE: irods_port - 1247
NOTICE: xmsg_port is not defined
NOTICE: irods_default_resource - demoResc
NOTICE: irods_zone - zone
NOTICE: irods_client_server_policy - CS_NEG_REFUSE
NOTICE: irods_client_server_negotiation - request_server_negotiation
NOTICE: irods_encryption_key_size - 32
NOTICE: irods_encryption_salt_size - 8
NOTICE: irods_encryption_num_hash_rounds - 16
NOTICE: irods_encryption_algorithm - AES-256-CBC
NOTICE: irods_default_hash_scheme - SHA256
NOTICE: irods_match_hash_policy - compatible
NOTICE: irods_gsi_server_dn is not defined
NOTICE: irods_debug is not defined
NOTICE: irods_log_level is not defined
NOTICE: irods_authentication_file_name is not defined
NOTICE: irods_ssl_ca_certificate_path is not defined
NOTICE: irods_ssl_ca_certificate_file is not defined
NOTICE: irods_ssl_verify_server is not defined
NOTICE: irods_ssl_certificate_chain_file is not defined
NOTICE: irods_ssl_certificate_key_file is not defined
NOTICE: irods_ssl_dh_params_file is not defined
NOTICE: irods_server_control_plane_key - TEMPORARY__32byte_ctrl_plane_key
NOTICE: irods_server_control_plane_encryption_num_hash_rounds - 16
NOTICE: irods_server_control_plane_encryption_algorithm - AES-256-CBC
NOTICE: irods_server_control_plane_port - 1248
```

**Comment by ccacciari** [comment]
changed the replication mechanism in the rules, hence the delayed execution mode is not required anymore
