### ISSUE TITLE
Centos 7.2 (python 2.7) and epicclient2.py failure

### ISSUE THREAD

**Issue by cookie33** [EUDAT-B2SAFE/B2SAFE-core#59]
Hi,

It seems that the epicclient2.py does not work in conjunction with Centos 7.2 and python 2.7 on it. This has been tested and proven to work on Centos 6.8 with python 2.6. If the following parameters are set in the credentials file:
```
reverse_username
reverse_password
```
These parameters are NOT read using the epicclient2.py and thus not used to invoke the b2handle library.
It seems following part is not working on this version:
```
def search(args):
    """perform search action"""

    # load credentials
    credentials = PIDClientCredentials.load_from_JSON(args.credpath)

    # set username and password for search
    if 'reverse_username' in credentials.get_config():
        reverselookup_username = credentials.get_config()['reverse_username']
    else:
        reverselookup_username = credentials.get_prefix()

    if 'reverse_password' in credentials.get_config():
        reverselookup_password = credentials.get_config()['reverse_password']
    else:
        reverselookup_password = credentials.get_password()

    # retrieve and set extra values
    extra_config = {}

    # setup connection to handle server
    client = EUDATHandleClient.instantiate_for_read_and_search(
        credentials.get_server_URL(),
        reverselookup_username,
        reverselookup_password,
        **extra_config)
```
The reverselookup_username and reverselookup_password are not set.
This happens for 2 functions: ```search``` and ```read```.

Because the b2handle library version 1.0.3 fixes a problem with these 2 parameters we can implement following:
```
def search(args):
    """perform search action"""

    # load credentials
    credentials = PIDClientCredentials.load_from_JSON(args.credpath)

    # retrieve and set extra values
    extra_config = {}

    # setup connection to handle server
    client = EUDATHandleClient.instantiate_with_credentials(
        credentials,
        **extra_config)
```
This also has to be implemented for the read action.

Than the credentials file has to be updated to use: ```reverselookup_username``` and ```reverselookup_password``` instead of ```reverse_username``` and ```reverse_password```

Robert Verkerk

**Comment by ccacciari** [comment]
The issue seems resoved
