### ISSUE TITLE
EUDATPidsForColl creates unsolicited pids on sibling collections

### ISSUE THREAD

**Issue by tsmeele** [EUDAT-B2SAFE/B2SAFE-core#74]
test{
  EUDATPidsForColl('/aliceZone/home/di4r-user15/SubCollection');
}
If there is another collection called '/aliceZone/home/di4r-user15/SubCollection2'  then that collection and its contents will also have PID's after the above rule has ended.

**Comment by cookie33** [comment]
We need do to two things:
* create a test to check this in `B2SAFE-core/scripts/tests/testB2SafeCmd/irodsb2safetest.py`
* fix the problem

**Comment by chStaiger** [comment]
There is a '/' missing in the two loops in EUDATPidsForColl:
foreach(*RowC in SELECT COLL_NAME WHERE COLL_NAME like '*collPath%')
--> foreach(*RowC in SELECT COLL_NAME WHERE COLL_NAME like '*collPath/%')

**Comment by ccacciari** [comment]
I agree, but I would change it to: WHERE COLL_NAME = '*sCollPath' || like '*sCollPath/%' , otherwise we lose the root collection and its first level files.

**Comment by ccacciari** [comment]
addressed in B2SAFE version 4.0.0, so it can be closed.
