### ISSUE TITLE
msiDataObjRsync in the rule EUDATRegDataRepl does not work as expected

### ISSUE THREAD

**Issue by ccacciari** [EUDAT-B2SAFE/B2SAFE-core#96]
We have tested the replication between two federated iRODS instances v4.2.0 and B2SAFE v4.0.0.
The two B2SAFE instances belong to different zones and in each zone different resources are defined.
On the source instance, the default resource is demoResc, on the target instance the default resource is cinecaRes1. In the core.re of each instance the PEP _acSetRescSchemeForCreate_ and _acSetRescSchemeForRepl_ are set to force the adoption of the default resource, regardless of what the client set. For example:

`msiSetDefaultResc("cinecaRes1","forced");`

However the execution of the EUDATReplication rule fails:

`irule -F eudatReplication2.r ERROR: rcExecMyRule error.  status = -24000 SYS_INTERNAL_NULL_INPUT_ERRLevel 0: DEBUG: execMicroService3: error when executing microserviceline 303, col 12, rule base eudat4            msiDataObjRsync(*source,"IRODS_TO_IRODS","null",*destination,*rsyncStatus);            
^caused by: DEBUG: msiDataObjRsync: rsDataObjRsync failed for /INGV/home/rods/san/archive/2017/IV/ACER/HHZ.D/IV.ACER..HHZ.D.2017.190, status = -24000`

Where cat _eudatReplication2.r_:

`Replication {    *registered = "true";    *recursive = "true";    *status = EUDATReplication(*source, *destination, *registered, *recursive, *response);    if (*status) {        writeLine("stdout", "Replica *source on *destination Success!");    }    else {        writeLine("stdout", "Replica *source on *destination Failed: *response");    }}INPUT *source=" /INGV/home/rods/san/archive/2017/IV/ACER/HHZ.D/IV.ACER..HHZ.D.2017.190",*destination="/CINECA01/home/EUDAT_EPOS/EPOSReplica/archive/2017/IV/ACER/HHZ.D/IV.ACER..HHZ.D.2017.190" OUTPUT ruleExecOut`

And on the target site the error shows that the microservice is trying to create the replica object using the source default resource:

`/home/irodsbuild/irods/server/core/src/objDesc.cpp:231:int initDataObjInfoWithInp(dataObjInfo_t , dataObjInp_t ) :  status [SYS_RESC_DOES_NOT_EXIST]  errno [] -- message []	[-]	/home/irodsbuild/irods/server/core/src/irods_resource_manager.cpp:1085:irods::error irods::resource_manager::hier_to_leaf_id(const std::string &, rodsLong_t &) :  status [SYS_RESC_DOES_NOT_EXIST]  errno [] -- message [demoResc]`

So the microservice msiDataObjRsync does not seem to honor the default resource setting in the core.re. It worked with iRODS v4.1.x .
It is not clear if it is a bug of the microservice or if it depends on some other configuration.
A possible solution would be to modify the eudat rule _EUDATReplication_  to accept the destination resource as input parameter and set it explicitly in the microservice msiDataObjRsync.
Also note that the icommand irsync works as expected, honouring the default resource settings.

**Comment by cookie33** [comment]
What happens if you upgrade both machines to iRODS 4.2.1 and use b2safe 4.0-1?

iRODS 4.2.0 is a vanilla version without bug fixes.

**Comment by cookie33** [comment]
And what does `core.re` state? For iRODS 4.1.8 it states:
```
#
# --------------------------------------------------------------------------
# The following are rules for data object operation
# Note that the msiOprDisallowed microservice can be used by all the rules
# to disallow the execution of certain actions.
# 1) acSetRescSchemeForCreate - This is the preprossing rule for creating a
# data object. It can be used for setting the resource selection scheme
# when creating a data object which is used by the put, copy and
# replicate operations. Currently, three preprocessing functions can be
# used by this rule:
#    msiSetNoDirectRescInp(rescList) - sets a list of resources that cannot
#      be used by a normal user directly. More than one resources can be
#      input using the character "%" as separator. e.g., resc1%resc2%resc3.
#      This function is optional, but if used, should be the first function
#      to execute because it screens the resource input.
#    msiSetDefaultResc(defaultRescList, optionStr) - sets the default resource.
#      From version 2.3 onward, this function is no longer mandatory, but
#      if it is used, if should be executed right after the screening
#      function msiSetNoDirectRescInp.
#      defaultResc - the resource to use if no resource is input. A "null"
#        means there is no defaultResc. More than one resources can be
#      input using the character "%" as separator.
#      optionStr - Can be "forced", "preferred" or "null". A "forced" input
#      means the defaultResc will be used regardless of the user input.
#      The forced action only apply to to users with normal privilege.
#    msiSetRescSortScheme(sortScheme) - set the scheme for
#      for selecting the best resource to use when creating a data object.
#      sortScheme - The sorting scheme. Valid scheme are "default",
#        "random", "byLoad" and "byRescClass". The "byRescClass" scheme will put the
#        cache class of resource on the top of the list. The "byLoad" scheme will put
#        the least loaded resource on the top of the list: in order to work properly,
#        the RMS system must be switched on in order to pick up the load information
#        for each server in the resource group list.
#        The scheme "random" and "byRescClass" can be applied in sequence. e.g.,
#        msiSetRescSortScheme(random); msiSetRescSortScheme(byRescClass)
#        will select randomly a cache class resource and put it on the
#        top of the list.
```

And what happens with a setting of preferred?
And maybe there is in iRODS 4.2. a new _acSetRescSchemeFor*_ ?

**Comment by cookie33** [comment]
Please make a very small test with just `msiDataObjRsync` between 2 zones. if it fails on `4.2.1` make a bug report at iRODS so it can be fixed on 4.2.2.

If it is a iRODS bug ask iRODS for a solution and do not fix/repair the b2safe code base. Only on your specific instance.

**Comment by cookie33** [comment]
There was no issue opened at iRODS. And NO tests performed at 4.2.1.
I would not include the fixes of now before a issue has been made at iRODS

**Comment by cookie33** [comment]
add issue at iRODS: https://github.com/irods/irods/issues/3719

**Comment by cookie33** [comment]
Hi,

did you test this with iRODS 4.2.2 or 4.2.1 whitout your fixes?

**Comment by cookie33** [comment]
Hi,

Can you test it as follows:
```
test_replication {
msiDataObjRsync(*source,"IRODS_TO_IRODS","null",*destination,*rsyncStatus);
}

INPUT *source="/INGV/home/rods/san/archive/2017/IV/ACER/HHZ.D/IV.ACER..HHZ.D.2017.190",*destination="/CINECA01/home/EUDAT_EPOS/EPOSReplica/archive/2017/IV/ACER/HHZ.D/IV.ACER..HHZ.D.2017.190"
OUTPUT ruleExecOut
```

This way we still now if it is present in iRODS 4.2.2

**Comment by ccacciari** [comment]
Hi Robert,

About the tests with INGV, yes we tried changing the source and target "msiSetDefaultResc", setting it to preferred, forced, null, but without any success. However about the iRODS version, only the target, Cineca, was at version 4.2.1, while the source, INGV was at 4.1.3. And yes I tried also to execute directly the "msiDataObjRsync" and I got the same result. However I was not able to replicate that error in my testbed, between a version 4.1.8 and 4.2.1, so I was reluctant to open a ticket to iRODS developers. I asked INGV what they wanted to do and they preferred to update their iRODS instance to the latest version and then try again. I'm still waiting their feedback.
However it is clear that it is not a bug of the B2SAFE rules, because we set explicitly the destination resource and it failed anyway. So I think we can close this ticket.

**Comment by cookie33** [comment]
In the header it stated you had the same error between 2 iRODS 4.2.0 instances and b2safe.

If it is NOT a problem can you than remove the extra code with *source_resc and *destination_resc from the devel branch. This makes it harder to debug and not needed.

The parameter `msiSetDefaultResc` at the destination side should take care off all.

And because you have a testbed with iRODS 4.2.2 and 2 zones. I was wondering if you could do a quick test at CINECA if it exists at 4.2.2 or NOT.

**Comment by ccacciari** [comment]
The error was not related to the v4.2, but to the old v4.1. The test with v4.2 seems to work fine. Then I close the ticket
