### ISSUE TITLE
workflow to update a DO

### ISSUE THREAD

**Issue by cookie33** [EUDAT-B2SAFE/B2SAFE-core#99]
The wiki has workflow examples.

Can a workflow be added of what to when a DO (digital Object) is updated?

So the following use cases:
1 DO is registered or iput in iRODS
2 DO gets PID
...
...
3 a new version of the DO with the same name is registered or put on top of the old DO. (NO versioning at all) 

What script has to be run? 

So the following use cases:
1 DO is registered or iput in iRODS
2 DO gets PID
3 DO is replicated to second B2SAFE site
...
...
4 a new version of the DO with the same name is registered or put on top of the old DO. (NO versioning at all) 

What script has to be run on the site A and the replication site?

And can also some examples be added like:
- Data replication example
- PID registration example

**Comment by ccacciari** [comment]
The information is available in the chapter Best Practices
